### ISSUE TITLE
feature: validate keys config source.

### ISSUE THREAD

**Issue by lukedirtwalker** [greenpau/go-authcrunch#28]
> A clear and concise description of what you want the system to do.

Currently when getting the keys from the config in `GetKeysFromConfig` we have a switch on the `cfg.Source`:
https://github.com/greenpau/go-authcrunch/blob/ff000238985d20d12c1aed31235d6509f3f45dd1/pkg/kms/key.go#L101
If the `cfg.Source` is neither `"config"` nor `"env"` it is silently ignored. I suggest to add the following default case in `switch`:
```go
	default:
		return nil, fmt.Errorf("unsupported source: %s", cfg.Source)
```

**Comment by greenpau** [comment]
@lukedirtwalker , thank you for reporting this! Please send PR.
