### ISSUE TITLE
question: Why are all the web UI assets unnecessarily obfuscated?

### ISSUE THREAD

**Issue by michaelhthomas** [greenpau/go-authcrunch#41]
All of the assets for the web interface of the authentication portal are contained in https://github.com/greenpau/go-authcrunch/blob/main/pkg/authn/ui/content.go. This file is presumably generated, but I am unable to find the source that it is generated from. It would be nice to be able to see the source `css` and `javascript` files for the web ui, both for creating custom templates / stylesheets and just for transparency's sake? Is there any reason why all of these things are minified and obfuscated, or would it be possible to store the original files in this repository?

**Comment by greenpau** [comment]
@michaelhthomas , these are tailwind css generated files. I like keeping thing the way the are. If someone wants different style, they can just use https://authp.github.io/docs/authenticate/ui-features#other-customization to create their own assets.
